### PR TITLE
fix: Disable updating peer dependencies when updatePeerDependencies is false.

### LINKED ISSUE #2269: Peer dependencies are updated regardless of "updatePeerDependencies" setting.
#### Environment details

  - OS: Linux
  - Node.js version: 18.19.0
  - npm version: 10.2.3
  - `release-please` version: 16.10.1

#### Steps to reproduce

  1. Use the node workspace plugin with at least 2 packages. For these instructions package A and package B.
  2. Package B has a peer and dev dependency on package A.
  4. Make a change to package A with a commit that results in a releasable unit.
  5. The package.json of B will have its peer dependency updated.

Example PR where this happened: https://github.com/launchdarkly/js-core/pull/418/files

Specific file:
https://github.com/launchdarkly/js-core/pull/418/files#diff-9838b4949cf31603774a130ab3f492f4afcb6f430996e05ac6c778692f45a10b

It is a common practice to have a peer dependency and a dev dependency on another package. This allows you to unit test with the package you use as a peer dependency. In the linked example the `node-server-dynamo` package should be tested with the latest package, but the peer dependency should be a version range.

### PR DESCRIPTION
**Pull request by kinyoklion**
The "updatePeerDependencies" option currently operates as a "considerPeerDependencies" option. What this means is that if a package only has a peer dependency on another, then that will not be considered and no update will be made (as if there was no dependency). If a package has a peer dependency as well as another dependency, for instance a dev dependency, then the peer dependency is updated regardless.

This propagates the "updatePeerDependencies" option to the PackageJson updater so that it can omit updates to the peer dependencies.

It isn't completely clear what the intended behavior here is. This update behavior matches my current use-case, but it is possible it could be a problem for others. In which case there could be two different options (but the current name does seem like it would impact peer dependency updates.)

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [na] Appropriate docs were updated (if necessary)

Fixes #2269
 🦕

### CODE REVIEW

File: __snapshots__/package-json.js [hunk 1]
```diff
@@ -1,3 +1,59 @@
...
+\t},
+\t"dependencies": {
+\t\t"camelcase": "^6.0.0",
+\t\t"decamelize": "^1.2.0"
+\t},
+\t"optionalDependencies": {
+\t\t"foo": "~0.1.0"
+\t},
+\t"peerDependencies": {
+\t\t"bar": ">= 1.0.0"
```
Comment (kinyoklion) [inline __snapshots__/package-json.js:44]: Test that validates the peer dependency is not updated.

File: test/updaters/package-json.ts [hunk 2]
```diff
@@ -36,6 +36,25 @@ describe('PackageJson', () => {
...
+      );
+      const versionsMap: VersionsMap = new Map();
+      versionsMap.set('camelcase', Version.parse('6.0.0'));
+      versionsMap.set('chai', Version.parse('4.2.1'));
+      versionsMap.set('foo', Version.parse('0.1.0'));
+      versionsMap.set('bar', Version.parse('2.3.4'));
+      const packageJson = new PackageJson({
+        version: Version.parse('14.0.0'),
+        versionsMap,
+        updatePeerDependencies: true,
```
Comment (kinyoklion) [inline test/updaters/package-json.ts:51]: This test implicitly dependended on the updater always updating the peer dependencies. So it was updated and produces the same output.

File: test/updaters/package-json.ts [hunk 3]
```diff
@@ -36,6 +36,25 @@ describe('PackageJson', () => {
...
+      });
+      const newContent = packageJson.updateContent(oldContent);
+      snapshot(newContent.replace(/\r\n/g, '\n'));
+    });
+
+    it('does not update peer dependencies by default', async () => {
```
Comment (kinyoklion) [inline test/updaters/package-json.ts:57]: New test which does not update peer dependencies.

**Review by chingor13 — APPROVED** [review]
Thank you!
