### PR TITLE
fix: skip component when manifest release does not include component

### LINKED ISSUE #1527: Manifest releaser always releases every package regardless of changes
Hi, 👋

#### Summary

It appears that packages (in the manifest) are always being released, regardless of whether their contents were edited or not. I believe the packages that haven't changed are inheriting the root package's version and being re-released?

#### Environment details

  - OS: Ubuntu 20.04.4 LTS (20220710.1)
  - Node.js version: -
  - npm version: -
  - `release-please` version: 13.18.7
  - `release-please-action` version: v3.2.8 (SHA: b910fcea1279e7744f01ca9c82f79502240ccf7c)

#### Steps to reproduce

  1. Make a change to one of the packages defined in the Manifest
  2. Merge the proposed pull-request
  3. Notice `release-please` create a new release for every package, not just those that changed

Affected pull request: https://github.com/axieum/minecord-rp-test/pull/2
Affected GitHub Actions run: https://github.com/axieum/minecord-rp-test/actions/runs/2682112305

Please find the GitHub Actions run logs here: [logs_6.zip](https://github.com/googleapis/release-please/files/9125991/logs_6.zip)

Thanks,
Jonathan.

### LINKED ISSUE #1536: manifest release creates wrong tags for packages when custom pr title uses version
Using manifest release with ` "group-pull-request-title-pattern"` leads to wrong tags in the github release.

Given this configuration and manifest:
```
// config
{
  "group-pull-request-title-pattern": "chore${scope}: release${component} ${version}",
  "packages": {
    ".": {},
    "apps/app1": {},
    "apps/app2": {},
    "apps/app3": {},
    "libs/lib1": {}
  }
```

```
// manifest
{
    ".": "1.34.0",
    "apps/app1": "7.91.0",
    "apps/app2": "1.31.0",
    "apps/app3": "1.0.11",
    "libs/lib1": "4.91.0"
}

```

The tags for all the apps and libs in the github release are created with app1-v1.34.0 app2-v1.34 ... instead of app1-v7.91.0 app2-v1.31.0 ...

Therefore release-please doesn't handle the next release correctly because it will take old commits into consideration, leading to several other errors

#### Environment details

  - `release-please` version: 'google-github-actions/release-please-action@v3' (SHA:63edea1103e00b7d8a5c96cbdc97cc9ebf7c037c)

### PR DESCRIPTION
**Pull request by chingor13**
When a multi-component release PR was merged, we were rejecting untouched components only because we didn't find a version. However, if the group pull request title pattern was overridden and provided a version, we would not reject the release.

Now, we reject components if we do not find release data for them in the pull request.

Fixes #1527 
Fixes #1536

### CODE REVIEW

File: src/strategies/base.ts [hunk 1]
```diff
@@ -489,13 +489,21 @@ export abstract class BaseStrategy implements Strategy {
       releaseData = pullRequestBody.releaseData[0];
     } else {
       // manifest release with multiple components
-      releaseData = pullRequestBody.releaseData.find(releaseData => {
+      releaseData = pullRequestBody.releaseData.find(datum => {
         return (
-          this.normalizeComponent(releaseData.component) ===
+          this.normalizeComponent(datum.component) ===
```
Comment (bcoe) [inline src/strategies/base.ts:494]: A comment would be useful to me, that mentions that `component` is one of the parsed elements from the pull request body.

**Review by bcoe — APPROVED** [review]
Left a note, regarding something I'd love to see documented.
