### PR TITLE
fix: cargo workspace cargo lock handling

### LINKED ISSUE #1250: cargo-workspace plugin does not handle Cargo.lock files correctly
#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: 16.13.2
  - npm version: 8.1.2
  - `release-please` version: 13.4.2

#### Steps to reproduce

  1. Create a rust workspace project (https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) containing a single package `crates/package`.
  2. Run release-pr and observe:
    1. release-please tries to add a patch for `crates/package/Cargo.lock`.
    2. release-please doesn't try to add a patch for `Cargo.lock`

When using a cargo workspace the individual crates within that workspace don't have their own Cargo.lock file. Rather, they share a single Cargo.lock file at the root of the workspace. Quoting from https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html:

> Notice that the workspace has only one Cargo.lock file at the top level of the workspace rather than having a Cargo.lock in each crate’s directory.

I'm happy to have a go at making this work correctly, I just need some pointers to make sure I head in the right direction.

### PR DESCRIPTION
**Pull request by gsrushton**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1250  🦕

### CODE REVIEW

File: src/plugins/cargo-workspace.ts [hunk 1]
```diff
@@ -285,6 +282,24 @@ export class CargoWorkspace extends WorkspacePlugin<CrateInfo> {
...
+    const root_candidate = candidates.find(c => c.path === ROOT_PROJECT_PATH);
+    if (!root_candidate) {
+      throw Error('Unable to find root candidate pull request');
+    }
+
+    root_candidate.pullRequest.updates.push({
+      path: 'Cargo.lock',
+      createIfMissing: false,
+      updater: new CargoLock(updatedVersions),
+    });
```
Comment (chingor13) [inline src/plugins/cargo-workspace.ts:298]: nit: let's keep our variable names lowerCamelCased. `root_candidate` -> `rootCandidate`

**Review by chingor13 — CHANGES_REQUESTED** [review]
Thanks! This looks good to me with the small nit of renaming a local variable.

File: src/plugins/cargo-workspace.ts (hunk 1 above)
Comment (gsrushton) [reply src/plugins/cargo-workspace.ts]: Done, obviously I was still in rust mode when I wrote this :)

**Review by chingor13 — APPROVED** [review]
