### PR TITLE
fix: update Cargo.lock for single Rust crate

### LINKED ISSUE #1372: Rust: Cargo.lock file not update in single crate project
Hey folks! Love the project 😄 
We're trying to get it up and running for https://github.com/starship/starship but have noticed that our lockfile isn't updating as part of the release PR.

I suspect that it may not be configured to update the lockfile for Rust projects that aren't workspaces.

#### Environment details

  - OS: macOS 12.1
  - Node.js version: v16.14.2
  - npm version: 8.5.0
  - `release-please` version: 13.8.1

#### Steps to reproduce

  1. Clone or fork Starship at https://github.com/starship/starship
  2. Push a commit tagged with `feat`
  3. Create or open a release PR using release-please:
		```sh
		release-please release-pr --token=$GITHUB_TOKEN --repo-url=starship/starship --release-type=rust
		```
  4. Observe that Cargo.toml is correctly updated but Cargo.lock is untouched.

### PR DESCRIPTION
**Pull request by matchai**
Fixes #1372

### Changes
- Populate the `versionsMap` for non-workspace Rust crates
- Create a separate test fixture for testing non-workspace crates
- Copy existing Rust test suite for non-workspace crate fixture 
- Add a test verifying that `versionsMap` is populated correctly in a basic crate

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

File: src/strategies/rust.ts [hunk 1]
```diff
@@ -101,6 +101,18 @@ export class Rust extends BaseStrategy {
...
+        logger.warn('unable to find Cargo.toml');
+        return updates;
+      }
+      const manifest = parseCargoManifest(manifestContent.parsedContent);
+      if (manifest.package?.name) {
+        versionsMap.set(manifest.package.name, version);
+      } else {
+        logger.warn('No crate package name found');
+      }
+
```
Comment (chingor13) [inline src/strategies/rust.ts:115]: Will `this.getDefaultPackageName()` work for this?

Comment (matchai) [reply src/strategies/rust.ts:115]: Yes! Much better! 😄

**Review by chingor13 — APPROVED** [review]
