### PR TITLE
fix(cargo-workspace): stop defaulting to updating all components

### LINKED ISSUE #1407: Spurious version bumps for workspace dependencies in cargo workspace
Similar to https://github.com/googleapis/release-please/issues/1403, but opening another issue because I'm not sure the root cause is identical.

- `release-please` version: 13.14.0
- Example: https://github.com/CBenoit/my-gh-actions-playground/pull/2
- [Link to repository after merging](https://github.com/CBenoit/my-gh-actions-playground/tree/b-v0.3.0)

#### Steps to reproduce

  1. Start with an initial monorepo containing a cargo workspace of two crates A and B.
  2. Make B depends on A by updating `B/Cargo.toml`.
  3. Push a `feat` commit for crate B only.
  4. Observe the issue.
    a. **A also have a patch version bump in the release PR, but with no change**, and a changelog consisting of a 'Dependencies' header and an empty body.
    b. **`.release-please-manifest.json` is NOT updated with the minor bump of B, resulting in a mismatch between the manifest and the reality.**
    c. The PR body is referring to A using the default package name instead of the one specified in `release-please-config.json` (if any)

### PR DESCRIPTION
**Pull request by chingor13**
It's unclear why we always bump cargo versions for untouched components.

Fixes #1407

### CODE REVIEW

File: src/plugins/cargo-workspace.ts [hunk 1]
```diff
@@ -82,17 +72,6 @@ interface CrateInfo {
  * into a single rust package.
  */
 export class CargoWorkspace extends WorkspacePlugin<CrateInfo> {
-  constructor(
-    github: GitHub,
-    targetBranch: string,
-    repositoryConfig: RepositoryConfig,
-    options: WorkspacePluginOptions = {}
-  ) {
-    super(github, targetBranch, repositoryConfig, {
```
Comment (bcoe) [inline src/plugins/cargo-workspace.ts:91]: @fasterthanlime, I'm curious what your motivation was for this default behavior?

@chingor13 question on my mind is whether we should still make this configurable.

**Review by bcoe — APPROVED** [review]
I'm curious what the motivation for this default behavior was, makes me wonder if it should be configurable.

File: src/plugins/cargo-workspace.ts (hunk 1 above)
Comment (chingor13) [reply src/plugins/cargo-workspace.ts:91]: Yes, we can expose the option in the manifest, but will do it separately.
