### PR TITLE
fix: allow brackets in custom pull request title

### LINKED ISSUE #1444: There are untagged, merged release PRs outstanding - aborting on other branch than default
When using `release-please-action` on another branch than the default one, the PR is correctly opened, but once merged it fails to create the release:

```shell
 ✔ Looking for latest release on branch: hotfix/v3.1.0-bug with prefix: <repository-name>
✔ Building releases
✔ Building strategies by path
✔ Building release for path: .
⚠ pullRequestTitlePattern miss the part of '${scope}'
⚠ pullRequestTitlePattern miss the part of '${component}'
⚠ pullRequestTitlePattern miss the part of '${version}'
✖ Bad pull request title: '[HOTFIX] - chore(hotfix/v3.1.0-bug): release 3.1.0-hotfix1'
✔ No release necessary for path: .

✔ Looking for latest release on branch: hotfix/v3.1.0-bug with prefix: <repository-name>
✔ Building pull requests
✔ Building strategies by path
✔ Collecting release commit SHAs
✔ Collecting commits since all latest releases
✔ Splitting 4 commits by path
✔ Building candidate release pull request for path: .
✔ Considering: 5 commits
⚠ There are untagged, merged release PRs outstanding - aborting
````

The PR is still labelled as `autorelease: pending`, thus the release is not created.

My configuration is the following one:

```shell
[...]
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: ${{ github.event.repository.name }}
          token: ${{ secrets.token }}
          default-branch: ${{ github.ref_name }}
          pull-request-title-pattern: "[HOTFIX] - chore${scope}: release${component} ${version}"
          monorepo-tags: false
```

There is a related issue on https://github.com/google-github-actions/release-please-action/issues/443

### PR DESCRIPTION
**Pull request by chingor13**
Fixes #1444

### CODE REVIEW

File: src/util/pull-request-title.ts [hunk 1]
```diff
@@ -39,10 +39,12 @@ export function generateMatchPattern(pullRequestTitlePattern?: string): RegExp {
     logger.warn("pullRequestTitlePattern miss the part of '${version}'");
   return new RegExp(
     `^${(pullRequestTitlePattern || DEFAULT_PR_TITLE_PATTERN)
-      .replace('${scope}', '(\\((?<branch>[\\w-.]+)\\))?')
+      .replace('[', '\\[')
```
Comment (bcoe) [inline src/util/pull-request-title.ts:42]: perhaps worth pulling in the dep `escape-string-regexp`, we already rely on it as a deep dep, keep the same tests.

**Review by bcoe — APPROVED** [review]

File: src/util/pull-request-title.ts (hunk 1 above)
Comment (chingor13) [reply src/util/pull-request-title.ts]: Note: v5 of that library is the only one with types and our current dependencies use v1 and v4. Additionally, I was having issues with ESM using that library. I added a TODO to handle all regex characters.

Comment (chingor13) [reply src/util/pull-request-title.ts]: Note: v5 of that library is the only one with types and our current dependencies use v1 and v4. Additionally, I was having issues with ESM using that library. I added a TODO to handle all regex characters.
