### PR TITLE
fix: read packageName from config

### LINKED ISSUE #1264: samples/package.json no longer updated during release
It appears that `samples/package.json` is no longer updated for Node.js release, see:

https://github.com/googleapis/google-api-nodejs-client/pull/2880
https://github.com/googleapis/nodejs-firestore/pull/1665

This results in the samples running against the wrong version of the library after the release is merged (noticed due to failing PRs on google-api-client).

### PR DESCRIPTION
**Pull request by bcoe**
Read packageName from config if not provided.

Fixes #1264

### CODE REVIEW

**Review by SurferJeffAtGoogle — APPROVED** [review]

File: src/strategies/base.ts [hunk 1]
```diff
@@ -227,6 +229,8 @@ export abstract class BaseStrategy implements Strategy {
       await this.buildVersionsMap(conventionalCommits),
       conventionalCommits
     );
+    this.packageName = this.packageName ?? (await this.getDefaultPackageName());
+    logger.debug('packageName', this.packageName);
```
Comment (chingor13) [inline src/strategies/base.ts:233]: This is potentially an unnecessary call. We should probably make this a memoizing getter and only call it when necessary.

File: test/strategies/node.ts [hunk 2]
```diff
@@ -132,6 +168,14 @@ describe('Node', () => {
       assertHasUpdate(updates, 'package-lock.json', PackageLockJson);
       assertHasUpdate(updates, 'npm-shrinkwrap.json', PackageLockJson);
       assertHasUpdate(updates, 'samples/package.json', SamplesPackageJson);
+      // Ensure that the packageName is used vs., the component
+      // when updating samples/package.json:
+      for (const update of updates) {
+        if (update.path === 'samples/package.json') {
```
Comment (chingor13) [inline test/strategies/node.ts:174]: The `assertHasUpdate()` method (line 170) returns the `Update` if found. This would eliminate the need to fin

File: test/strategies/node.ts [hunk 3]
```diff
@@ -113,13 +115,47 @@ describe('Node', () => {
...
+      expect(pullRequest!.version?.toString()).to.eql(expectedVersion);
+    });
   });
   describe('buildUpdates', () => {
     it('builds common files', async () => {
       const strategy = new Node({
         targetBranch: 'main',
         github,
         component: 'google-cloud-automl',
+        packageName: 'google-cloud-automl-pkg',
```
[the remark this answers is not in the document]
Comment (bcoe) [reply test/strategies/node.ts:158]: Yes but because `component` was used in place of `packageName` this test case would always have passed, the issue is if the packageName and component diverge.
