### PR TITLE
fix: address false-positive matches for autorelease branch naming

### LINKED ISSUE #1310: "Error parsing branch name" for branches like "v3.3.x"
1) Is this a client library issue or a product issue?

Issue with release-please, used via release-please-action to automate releases of google/shaka-player.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/release-please/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

This is very similar to issue #1226 and related to the fix in PR #1227.  I think the fix could be improved. 
 I have an analysis of how it failed for my repo, and what could be done to make release-please a bit more resilient in this case.

3) Do you have a support contract?

No, but I'm a Googler working on an official Google project.

#### Environment details

  - OS: Ubuntu 20.04 via GitHub Actions (ubuntu-latest)
  - Node.js version: 16.14.0
  - npm version: 8.3.1
  - `release-please` version: 13.4.10 via release-please-action 3.1.2

#### Steps to reproduce

  1. Set up release-please or release-please-action on a repo with a branch named something like v3.3.x (as we have in google/shaka-player)
  2. Merge a release PR

#### Analysis

Pattern matching in src/util/branch-name.ts goes like this:

```ts
function getAllResourceNames(): BranchNameType[] {
  return [
    AutoreleaseBranchName,
    ComponentBranchName,
    DefaultBranchName,
    V12ComponentBranchName,
    V12DefaultBranchName,
  ];
}

// ...

      const branchNameClass = getAllResourceNames().find(clazz => {
        return clazz.matches(branchName);
      });
```

Since AutoreleaseBranchName appears before DefaultBranchName, that matches something like `release-please--branches--v3.3.x` based on:

```ts
const AUTORELEASE_PATTERN =
  /^release-?(?<component>[\w-.]*)?-v(?<version>[0-9].*)$/;
```

It thinks `please--branches-` is the component.  However, when constructed, AutoreleaseBranchName throws from the constructor because `Version.parse` can't parse `v3.3.x` (the branch name):

```ts
  constructor(branchName: string) {
    super(branchName);
    const match = branchName.match(AUTORELEASE_PATTERN);
    if (match?.groups) {
      this.component = match.groups['component'];
      this.version = Version.parse(match.groups['version']);
    }
  }
```

See https://github.com/google/shaka-player/issues/3968

#### Proposal

First, I would suggest we change the matching such that the component can't be `please--branches-`.  I think this alone would be sufficient for me and my case.  I'll go ahead and send a PR for that.

However, I would suggest that we also go a bit further.  If an exception is thrown in the constructor of one of these classes, I would suggest that we fall back to the next match in the list instead of returning undefined.  This would mean replacing `getAllResourceNames().find(...)` with a loop over `match()` and `new`, with try/catch inside the loop instead of outside.  If the maintainers are concerned about this step, I would be happy to drop it.

### PR DESCRIPTION
**Pull request by joeyparrish**
Autorelease branch naming can mistakenly match for any branch
beginning with a v.  A PR branch like
"release-please--branches--v3.3.x" will be treated as an autorelease
branch for a component called "please--branches-".

If the branch name is a valid semver, the wrong class will be chosen
to parse the branch name, and later steps will fail.  If it's not a
valid semver, then branch parsing will completely fail.

This excludes these false-positive matches by excluding branches which
start with "release-please--branches".

- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1310 🦕

### CODE REVIEW

File: src/util/branch-name.ts [hunk 1]
```diff
@@ -103,7 +103,22 @@ const AUTORELEASE_PATTERN =
...
+    if (!match) {
+      return false;
+    }
+
+    // The regex can match release branches that should belong to
+    // DefaultBranchName (such as release-please--branches--v3.3.x). Make sure
+    // the component, if present, isn't something suspicious. See also
+    // https://github.com/googleapis/release-please/issues/1310
+    if (match?.groups) {
+      const component = match.groups['component'];
```
Comment (bcoe) [inline src/util/branch-name.ts:116]:
```suggestion
      const component = match.groups.component
```

stylistic-nit.

File: src/util/branch-name.ts [hunk 2]
```diff
@@ -103,7 +103,22 @@ const AUTORELEASE_PATTERN =
   /^release-?(?<component>[\w-.]*)?-v(?<version>[0-9].*)$/;
 class AutoreleaseBranchName extends BranchName {
   static matches(branchName: string): boolean {
-    return !!branchName.match(AUTORELEASE_PATTERN);
+    const match = branchName.match(AUTORELEASE_PATTERN);
```
Comment (bcoe) [inline src/util/branch-name.ts:106]: If I'm understanding the problem properly, could this safely be simplified to:

```
const BRANCH_PREFIX= 'release-please--branches';
if (branchName.startsWith(BRANCH_PREFIX)) return false;
```

**Review by bcoe — CHANGES_REQUESTED** [review]
Left a nit and a question.

File: src/util/branch-name.ts (hunk 1 above)
Comment (joeyparrish) [reply src/util/branch-name.ts:116]: Thanks, I'm new to TS.  Still doing JS + Closure in my own projects.

File: src/util/branch-name.ts (hunk 2 above)
Comment (joeyparrish) [reply src/util/branch-name.ts:106]: Ah, yes, that works.  I'll do that.

**Review by chingor13 — APPROVED** [review]

**Review by bcoe — APPROVED** [review]
