### PR TITLE
fix: associated pull requests should match merge commit sha

### LINKED ISSUE #818: latestTag can report the wrong version number
Example: https://github.com/googleapis/java-bigtable-hbase/pull/2827

The PR title is incorrectly finding the version to release. The graphQL is confused because associatedPullRequests includes a different, still-open pull request rather than the pull request that made the commit.

### PR DESCRIPTION
**Pull request by chingor13**
This should fix some misidentified release PRs. Sometimes, multiple pull requests are associated with a commit. In those cases, match the merge commit sha against the commit sha to find the pull request that made that commit.

Fixes #818

### CODE REVIEW

**Comment by chingor13** [comment]
cc @kolea2

File: src/github.ts [hunk 1]
```diff
@@ -701,8 +707,12 @@ export class GitHub {
...
           files: [] as string[],
         };
-        if (graphCommit.associatedPullRequests.nodes.length > 0) {
-          const pullRequest = graphCommit.associatedPullRequests.nodes[0];
+        const pullRequest = graphCommit.associatedPullRequests.nodes.find(
+          pr => {
+            return pr.mergeCommit && pr.mergeCommit.oid === graphCommit.sha;
+          }
+        );
+        if (pullRequest) {
```
Comment (joeldodge79) [inline src/github.ts:715]: makes sense though I'd be curious to understand better what a `pr.mergeCommit.oid` is in different cases of how the PR could have been merged (e.g. traditional "create a merge commit", vs "squash", vs "rebase"). I guess whatever the PR-Merge strategy, this logic will find the PR that literally is the reason for this `graphCommit.sha/pr.mergeCommit.oid` to exist in the history of the branch at all.

Comment (chingor13) [reply src/github.ts:715]: Example responses:
* Rebase/merge [PR](https://github.com/chingor13/release-please-test/pull/6) [graphql](https://gist.github.com/chingor13/8bcdaf992020d89d0c404a3bbbbeff9a#file-gistfile1-json-L71-L154)
* Merge [PR](https://github.com/chingor13/release-please-test/pull/7) [graphql](https://gist.github.com/chingor13/8bcdaf992020d89d0c404a3bbbbeff9a#file-gistfile1-json-L8-L70)

**Review by bcoe — APPROVED** [review]
