### PR TITLE
fix(rust): Rust strategy should update root Cargo files in a workspace

### LINKED ISSUE #1096: release-please should increment version in `Cargo.toml`.
release-please seems to update `Cargo.lock` but not `Cargo.toml` when revving a release. I am using the recommended GitHub Action.

Sadly my repo is private, so I can not point you to it, but here is a screenshot:

cargo

Also, the CI checks never kick off for a reason I have not yet determined, but I expect this is not a release-please problem.

### LINKED ISSUE #1170: Cargo.toml not updated for rust workspaces
#### Environment details

  - OS: ubuntu-latest (Running on github actions)
  - Node.js version: -
  - npm version: -
  - `release-please` version: `GoogleCloudPlatform/release-please-action@v2.35.0`

#### Steps to reproduce

1. Create a simple rust project: 

```sh
cargo new release-please-issue-1170
cd release-please-issue-1170
cargo new sub-crate
```

2. Make it a workspace by a adding to the root `Cargo.toml`:

 ```toml
[workspace]
members = ["sub-crate"]
 ```

3. Write `.github/workflows/release.yml`:

```yaml
name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: rust
```

4. Commit,tag `v0.1.0` and push to a github repo.

5. Commit (and push) a "feature": `git commit -m "feat: New shiny feature"' --allow-empty`
6. Observe the created PR. The two `Cargo.toml` are not updated! (Only the `Cargo.lock` is)

### PR DESCRIPTION
**Pull request by chingor13**
* Cargo.toml updater now updates the main package version from the updater's version
* cargo-workspace merges the root component's updates
* rust strategy now updates all workspace members versions in sync (overridden by cargo-workspace plugin if configured)

Fixes #1170
Fixes #1096

### CODE REVIEW

**Comment by chingor13** [comment]
Hmm, this is colliding with the cargo-manifest plugin. If you set the root component, it updates all the submodules to the same version, then the cargo-manifest plugin runs effectively doing nothing.

**Comment by chingor13** [comment]
cc @jcornaz

File: src/strategies/rust.ts [hunk 1]
```diff
@@ -44,36 +44,66 @@ export class Rust extends BaseStrategy {
...
       logger.info(
         `found workspace with ${members.length} members, upgrading all`
       );
+
+      // Collect submodule names to update
+      const manifestsByPath: Map<string, GitHubFileContents> = new Map();
       for (const member of members) {
-        manifestPaths.push(`${member}/Cargo.toml`);
+        const manifestPath = `${member}/Cargo.toml`;
+        const manifestContent = await this.getContent(manifestPath);
```
Comment (bcoe) [inline src/strategies/rust.ts:66]: Feels like there's enough going on here that it might benefit from being broken out into a private helper function.

File: test/strategies/rust.ts [hunk 2]
```diff
@@ -147,6 +153,7 @@ describe('Rust', () => {
       const updates = release!.updates;
       assertHasUpdate(updates, 'crates/crate1/Cargo.toml', CargoToml);
       assertHasUpdate(updates, 'crates/crate2/Cargo.toml', CargoToml);
+      assertHasUpdate(updates, 'Cargo.toml', CargoToml);
```
Comment (bcoe) [inline test/strategies/rust.ts:156]: Is this the main regression here, that the root Cargo.toml wasn't updated?

**Review by bcoe — APPROVED** [review]
:heavy_check_mark: since it's probably good to get a fix out to folks for this. I think it might be worth refactoring the logic for collecting submodule updates into a private helper?

File: test/strategies/rust.ts (hunk 2 above)
Comment (chingor13) [reply test/strategies/rust.ts:156]: Yeah, this was the initial failing test written to capture the bug
