### PR TITLE
fix: Update version string in Terraform submodule README files

### LINKED ISSUE #637: [Terraform] Update submodule README versions
Currently, the Terraform module releaser only [updates](https://github.com/googleapis/release-please/blob/master/src/releasers/terraform-module.ts#L81-L88) the root README. Instead, it should update the version tag in all submodules so that examples don't get out of date ([context](https://github.com/terraform-google-modules/terraform-google-lb-http/pull/140)).

### PR DESCRIPTION
**Pull request by morgante**
Fixes #637.

### CODE REVIEW

File: test/releasers/terraform-module.ts [hunk 1]
```diff
@@ -50,16 +51,23 @@ describe('terraform-module', () => {
...
       ],
+      findReadmeFiles: [
+        'readme.md',
+        // 'module-submodule/modules/sub-module-missing-versions/README.md',
+        'module-submodule/modules/sub-module-with-version/readme.md'
+      ],
       readFilePaths: [
         'module-submodule/readme.md',
         'module-submodule/versions.tf',
+        // 'module-submodule/modules/sub-module-missing-versions/README.md',
```
Comment (bharathkkb) [inline test/releasers/terraform-module.ts:62]: All readme.md files would be read first as we have the readmeFiles update before the versionFiles update. Also missing `'module-submodule/modules/sub-module-with-version/readme.md',`
```ts
      readFilePaths: [
        'module-submodule/readme.md',
        'module-submodule/modules/sub-module-missing-versions/README.md',
        'module-submodule/modules/sub-module-with-version/readme.md',
        'module-submodule/versions.tf',
        'module-submodule/modules/sub-module-with-version/versions.tf',
      ]
```

**Review by bcoe — APPROVED** [review]

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
thanks 🥳
